### PR TITLE
add baccyflap.com

### PR DESCRIPTION
**Pull request by ghost**
i'm ready coach

### CODE REVIEW

**Comment by pionaiki** [comment]
This webring is for members of our Mastodon/Fedi community. You don't seem to be in it. Correct me if i'm wrong.

**Comment by ghost** [comment]
You are correct - though the ring page does not say that that is what this webring is for.

**Comment by pionaiki** [comment]
I guess so, the github readme does tho

**Comment by ghost** [comment]
Where does it say that? I may be looking at the wrong document because I can't find it.

**Pull request closed without merging**
